version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    working_dir: /var/www
    volumes: 
      - ./:/var/www/

  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=${SPICEDB_GRPC_PRESHARED_KEY:-secret}"
      - "SPICEDB_DATASTORE_ENGINE=mysql"
      - "SPICEDB_DATASTORE_CONN_URI=root:${MYSQL_ROOT_PASSWORD:-secret}@tcp(${MYSQL_HOST:-mysql}:3306)/${MYSQL_DATABASE:-spicedb}?parseTime=true"
    depends_on:
      - "migrate"

  migrate:
    image: "authzed/spicedb"
    command: "migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=mysql"
      - "SPICEDB_DATASTORE_CONN_URI=root:${MYSQL_ROOT_PASSWORD:-secret}@tcp(${MYSQL_HOST:-mysql}:3306)/${MYSQL_DATABASE:-spicedb}?parseTime=true"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}"
      - "MYSQL_DATABASE=spicedb"
