<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.DeveloperError</code>
 */
class DeveloperError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>uint32 line = 2 [json_name = "line"];</code>
     */
    protected $line = 0;
    /**
     * Generated from protobuf field <code>uint32 column = 3 [json_name = "column"];</code>
     */
    protected $column = 0;
    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.Source source = 4 [json_name = "source"];</code>
     */
    protected $source = 0;
    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.ErrorKind kind = 5 [json_name = "kind"];</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>repeated string path = 6 [json_name = "path"];</code>
     */
    private $path;
    /**
     * context holds the context for the error. For schema issues, this will be the
     * name of the object type. For relationship issues, the full relationship string.
     *
     * Generated from protobuf field <code>string context = 7 [json_name = "context"];</code>
     */
    protected $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type int $line
     *     @type int $column
     *     @type int $source
     *     @type int $kind
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $path
     *     @type string $context
     *           context holds the context for the error. For schema issues, this will be the
     *           name of the object type. For relationship issues, the full relationship string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 line = 2 [json_name = "line"];</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Generated from protobuf field <code>uint32 line = 2 [json_name = "line"];</code>
     * @param int $var
     * @return $this
     */
    public function setLine($var)
    {
        GPBUtil::checkUint32($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 column = 3 [json_name = "column"];</code>
     * @return int
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * Generated from protobuf field <code>uint32 column = 3 [json_name = "column"];</code>
     * @param int $var
     * @return $this
     */
    public function setColumn($var)
    {
        GPBUtil::checkUint32($var);
        $this->column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.Source source = 4 [json_name = "source"];</code>
     * @return int
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.Source source = 4 [json_name = "source"];</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V0\DeveloperError\Source::class);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.ErrorKind kind = 5 [json_name = "kind"];</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError.ErrorKind kind = 5 [json_name = "kind"];</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V0\DeveloperError\ErrorKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string path = 6 [json_name = "path"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>repeated string path = 6 [json_name = "path"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPath($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->path = $arr;

        return $this;
    }

    /**
     * context holds the context for the error. For schema issues, this will be the
     * name of the object type. For relationship issues, the full relationship string.
     *
     * Generated from protobuf field <code>string context = 7 [json_name = "context"];</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * context holds the context for the error. For schema issues, this will be the
     * name of the object type. For relationship issues, the full relationship string.
     *
     * Generated from protobuf field <code>string context = 7 [json_name = "context"];</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, True);
        $this->context = $var;

        return $this;
    }

}

