<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V0\DeveloperError\Source instead.
     * @deprecated
     */
    class DeveloperError_Source {}
}
class_exists(DeveloperError\Source::class);
@trigger_error('Authzed\Api\V0\DeveloperError_Source is deprecated and will be removed in the next major release. Use Authzed\Api\V0\DeveloperError\Source instead', E_USER_DEPRECATED);

