<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V0\DeveloperError\ErrorKind instead.
     * @deprecated
     */
    class DeveloperError_ErrorKind {}
}
class_exists(DeveloperError\ErrorKind::class);
@trigger_error('Authzed\Api\V0\DeveloperError_ErrorKind is deprecated and will be removed in the next major release. Use Authzed\Api\V0\DeveloperError\ErrorKind instead', E_USER_DEPRECATED);

