<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.EditCheckRequest</code>
 */
class EditCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v0.RequestContext context = 1 [json_name = "context"];</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple check_relationships = 2 [json_name = "checkRelationships"];</code>
     */
    private $check_relationships;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V0\RequestContext $context
     *     @type array<\Authzed\Api\V0\RelationTuple>|\Google\Protobuf\Internal\RepeatedField $check_relationships
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.RequestContext context = 1 [json_name = "context"];</code>
     * @return \Authzed\Api\V0\RequestContext|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.RequestContext context = 1 [json_name = "context"];</code>
     * @param \Authzed\Api\V0\RequestContext $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V0\RequestContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple check_relationships = 2 [json_name = "checkRelationships"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCheckRelationships()
    {
        return $this->check_relationships;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple check_relationships = 2 [json_name = "checkRelationships"];</code>
     * @param array<\Authzed\Api\V0\RelationTuple>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCheckRelationships($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V0\RelationTuple::class);
        $this->check_relationships = $arr;

        return $this;
    }

}

