<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.EditCheckResult</code>
 */
class EditCheckResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v0.RelationTuple relationship = 1 [json_name = "relationship"];</code>
     */
    protected $relationship = null;
    /**
     * Generated from protobuf field <code>bool is_member = 2 [json_name = "isMember"];</code>
     */
    protected $is_member = false;
    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 3 [json_name = "error"];</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V0\RelationTuple $relationship
     *     @type bool $is_member
     *     @type \Authzed\Api\V0\DeveloperError $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.RelationTuple relationship = 1 [json_name = "relationship"];</code>
     * @return \Authzed\Api\V0\RelationTuple|null
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    public function hasRelationship()
    {
        return isset($this->relationship);
    }

    public function clearRelationship()
    {
        unset($this->relationship);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.RelationTuple relationship = 1 [json_name = "relationship"];</code>
     * @param \Authzed\Api\V0\RelationTuple $var
     * @return $this
     */
    public function setRelationship($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V0\RelationTuple::class);
        $this->relationship = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_member = 2 [json_name = "isMember"];</code>
     * @return bool
     */
    public function getIsMember()
    {
        return $this->is_member;
    }

    /**
     * Generated from protobuf field <code>bool is_member = 2 [json_name = "isMember"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMember($var)
    {
        GPBUtil::checkBool($var);
        $this->is_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 3 [json_name = "error"];</code>
     * @return \Authzed\Api\V0\DeveloperError|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 3 [json_name = "error"];</code>
     * @param \Authzed\Api\V0\DeveloperError $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V0\DeveloperError::class);
        $this->error = $var;

        return $this;
    }

}

