<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.EditCheckResponse</code>
 */
class EditCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.DeveloperError request_errors = 1 [json_name = "requestErrors"];</code>
     */
    private $request_errors;
    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.EditCheckResult check_results = 2 [json_name = "checkResults"];</code>
     */
    private $check_results;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V0\DeveloperError[]|\Google\Protobuf\Internal\RepeatedField $request_errors
     *     @type \Authzed\Api\V0\EditCheckResult[]|\Google\Protobuf\Internal\RepeatedField $check_results
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.DeveloperError request_errors = 1 [json_name = "requestErrors"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequestErrors()
    {
        return $this->request_errors;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.DeveloperError request_errors = 1 [json_name = "requestErrors"];</code>
     * @param \Authzed\Api\V0\DeveloperError[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequestErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V0\DeveloperError::class);
        $this->request_errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.EditCheckResult check_results = 2 [json_name = "checkResults"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCheckResults()
    {
        return $this->check_results;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.EditCheckResult check_results = 2 [json_name = "checkResults"];</code>
     * @param \Authzed\Api\V0\EditCheckResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCheckResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V0\EditCheckResult::class);
        $this->check_results = $arr;

        return $this;
    }

}

