<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.FormatSchemaResponse</code>
 */
class FormatSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 1 [json_name = "error"];</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>string formatted_schema = 2 [json_name = "formattedSchema"];</code>
     */
    protected $formatted_schema = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V0\DeveloperError $error
     *     @type string $formatted_schema
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 1 [json_name = "error"];</code>
     * @return \Authzed\Api\V0\DeveloperError|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.DeveloperError error = 1 [json_name = "error"];</code>
     * @param \Authzed\Api\V0\DeveloperError $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V0\DeveloperError::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string formatted_schema = 2 [json_name = "formattedSchema"];</code>
     * @return string
     */
    public function getFormattedSchema()
    {
        return $this->formatted_schema;
    }

    /**
     * Generated from protobuf field <code>string formatted_schema = 2 [json_name = "formattedSchema"];</code>
     * @param string $var
     * @return $this
     */
    public function setFormattedSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->formatted_schema = $var;

        return $this;
    }

}

