<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.LookupShareResponse</code>
 */
class LookupShareResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v0.LookupShareResponse.LookupStatus status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string schema = 2 [json_name = "schema"];</code>
     */
    protected $schema = '';
    /**
     * Generated from protobuf field <code>string relationships_yaml = 3 [json_name = "relationshipsYaml"];</code>
     */
    protected $relationships_yaml = '';
    /**
     * Generated from protobuf field <code>string validation_yaml = 4 [json_name = "validationYaml"];</code>
     */
    protected $validation_yaml = '';
    /**
     * Generated from protobuf field <code>string assertions_yaml = 5 [json_name = "assertionsYaml"];</code>
     */
    protected $assertions_yaml = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $schema
     *     @type string $relationships_yaml
     *     @type string $validation_yaml
     *     @type string $assertions_yaml
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.LookupShareResponse.LookupStatus status = 1 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.LookupShareResponse.LookupStatus status = 1 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V0\LookupShareResponse\LookupStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema = 2 [json_name = "schema"];</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>string schema = 2 [json_name = "schema"];</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relationships_yaml = 3 [json_name = "relationshipsYaml"];</code>
     * @return string
     */
    public function getRelationshipsYaml()
    {
        return $this->relationships_yaml;
    }

    /**
     * Generated from protobuf field <code>string relationships_yaml = 3 [json_name = "relationshipsYaml"];</code>
     * @param string $var
     * @return $this
     */
    public function setRelationshipsYaml($var)
    {
        GPBUtil::checkString($var, True);
        $this->relationships_yaml = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string validation_yaml = 4 [json_name = "validationYaml"];</code>
     * @return string
     */
    public function getValidationYaml()
    {
        return $this->validation_yaml;
    }

    /**
     * Generated from protobuf field <code>string validation_yaml = 4 [json_name = "validationYaml"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidationYaml($var)
    {
        GPBUtil::checkString($var, True);
        $this->validation_yaml = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assertions_yaml = 5 [json_name = "assertionsYaml"];</code>
     * @return string
     */
    public function getAssertionsYaml()
    {
        return $this->assertions_yaml;
    }

    /**
     * Generated from protobuf field <code>string assertions_yaml = 5 [json_name = "assertionsYaml"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssertionsYaml($var)
    {
        GPBUtil::checkString($var, True);
        $this->assertions_yaml = $var;

        return $this;
    }

}

