<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V0\LookupShareResponse\LookupStatus instead.
     * @deprecated
     */
    class LookupShareResponse_LookupStatus {}
}
class_exists(LookupShareResponse\LookupStatus::class);
@trigger_error('Authzed\Api\V0\LookupShareResponse_LookupStatus is deprecated and will be removed in the next major release. Use Authzed\Api\V0\LookupShareResponse\LookupStatus instead', E_USER_DEPRECATED);

