<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/core.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.RelationReference</code>
 */
class RelationReference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace", (.validate.rules) = {</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation", (.validate.rules) = {</code>
     */
    protected $relation = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $relation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace", (.validate.rules) = {</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation", (.validate.rules) = {</code>
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation = $var;

        return $this;
    }

}

