<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.RequestContext</code>
 */
class RequestContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string schema = 1 [json_name = "schema"];</code>
     */
    protected $schema = '';
    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple relationships = 2 [json_name = "relationships"];</code>
     */
    private $relationships;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $schema
     *     @type \Authzed\Api\V0\RelationTuple[]|\Google\Protobuf\Internal\RepeatedField $relationships
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string schema = 1 [json_name = "schema"];</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>string schema = 1 [json_name = "schema"];</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple relationships = 2 [json_name = "relationships"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRelationships()
    {
        return $this->relationships;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v0.RelationTuple relationships = 2 [json_name = "relationships"];</code>
     * @param \Authzed\Api\V0\RelationTuple[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRelationships($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V0\RelationTuple::class);
        $this->relationships = $arr;

        return $this;
    }

}

