<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/developer.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.UpgradeSchemaRequest</code>
 */
class UpgradeSchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string namespace_configs = 1 [json_name = "namespaceConfigs"];</code>
     */
    private $namespace_configs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $namespace_configs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string namespace_configs = 1 [json_name = "namespaceConfigs"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNamespaceConfigs()
    {
        return $this->namespace_configs;
    }

    /**
     * Generated from protobuf field <code>repeated string namespace_configs = 1 [json_name = "namespaceConfigs"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNamespaceConfigs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->namespace_configs = $arr;

        return $this;
    }

}

