<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v0/core.proto

namespace Authzed\Api\V0;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authzed.api.v0.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    protected $user_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V0\ObjectAndRelation $userset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V0\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.ObjectAndRelation userset = 2 [json_name = "userset", (.validate.rules) = {</code>
     * @return \Authzed\Api\V0\ObjectAndRelation|null
     */
    public function getUserset()
    {
        return $this->readOneof(2);
    }

    public function hasUserset()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v0.ObjectAndRelation userset = 2 [json_name = "userset", (.validate.rules) = {</code>
     * @param \Authzed\Api\V0\ObjectAndRelation $var
     * @return $this
     */
    public function setUserset($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V0\ObjectAndRelation::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getUserOneof()
    {
        return $this->whichOneof("user_oneof");
    }

}

