<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LookupSubjectsResponse contains a single matching subject object ID for the
 * requested subject object type on the permission or relation.
 *
 * Generated from protobuf message <code>authzed.api.v1.LookupSubjectsResponse</code>
 */
class LookupSubjectsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken looked_up_at = 1 [json_name = "lookedUpAt"];</code>
     */
    protected $looked_up_at = null;
    /**
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     *
     * Generated from protobuf field <code>string subject_object_id = 2 [json_name = "subjectObjectId"];</code>
     */
    protected $subject_object_id = '';
    /**
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     *
     * Generated from protobuf field <code>repeated string excluded_subject_ids = 3 [json_name = "excludedSubjectIds"];</code>
     */
    private $excluded_subject_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V1\ZedToken $looked_up_at
     *     @type string $subject_object_id
     *           subject_object_id is the Object ID of the subject found. May be a `*` if
     *           a wildcard was found.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $excluded_subject_ids
     *           excluded_subject_ids are the Object IDs of the subjects excluded. This list
     *           will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     *           will only be populated if exclusions exist from the wildcard.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1\PermissionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken looked_up_at = 1 [json_name = "lookedUpAt"];</code>
     * @return \Authzed\Api\V1\ZedToken|null
     */
    public function getLookedUpAt()
    {
        return $this->looked_up_at;
    }

    public function hasLookedUpAt()
    {
        return isset($this->looked_up_at);
    }

    public function clearLookedUpAt()
    {
        unset($this->looked_up_at);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken looked_up_at = 1 [json_name = "lookedUpAt"];</code>
     * @param \Authzed\Api\V1\ZedToken $var
     * @return $this
     */
    public function setLookedUpAt($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->looked_up_at = $var;

        return $this;
    }

    /**
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     *
     * Generated from protobuf field <code>string subject_object_id = 2 [json_name = "subjectObjectId"];</code>
     * @return string
     */
    public function getSubjectObjectId()
    {
        return $this->subject_object_id;
    }

    /**
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     *
     * Generated from protobuf field <code>string subject_object_id = 2 [json_name = "subjectObjectId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectObjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_object_id = $var;

        return $this;
    }

    /**
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     *
     * Generated from protobuf field <code>repeated string excluded_subject_ids = 3 [json_name = "excludedSubjectIds"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExcludedSubjectIds()
    {
        return $this->excluded_subject_ids;
    }

    /**
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     *
     * Generated from protobuf field <code>repeated string excluded_subject_ids = 3 [json_name = "excludedSubjectIds"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExcludedSubjectIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->excluded_subject_ids = $arr;

        return $this;
    }

}

