<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/schema_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ReadSchemaRequest returns the schema from the database.
 *
 * Generated from protobuf message <code>authzed.api.v1.ReadSchemaRequest</code>
 */
class ReadSchemaRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1\SchemaService::initOnce();
        parent::__construct($data);
    }

}

