<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1/permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ReadRelationshipsRequest specifies one or more filters used to read matching
 * relationships within the system.
 *
 * Generated from protobuf message <code>authzed.api.v1.ReadRelationshipsRequest</code>
 */
class ReadRelationshipsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v1.Consistency consistency = 1 [json_name = "consistency"];</code>
     */
    protected $consistency = null;
    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [json_name = "relationshipFilter", (.validate.rules) = {</code>
     */
    protected $relationship_filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V1\Consistency $consistency
     *     @type \Authzed\Api\V1\RelationshipFilter $relationship_filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1\PermissionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Consistency consistency = 1 [json_name = "consistency"];</code>
     * @return \Authzed\Api\V1\Consistency|null
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    public function hasConsistency()
    {
        return isset($this->consistency);
    }

    public function clearConsistency()
    {
        unset($this->consistency);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Consistency consistency = 1 [json_name = "consistency"];</code>
     * @param \Authzed\Api\V1\Consistency $var
     * @return $this
     */
    public function setConsistency($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Consistency::class);
        $this->consistency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [json_name = "relationshipFilter", (.validate.rules) = {</code>
     * @return \Authzed\Api\V1\RelationshipFilter|null
     */
    public function getRelationshipFilter()
    {
        return $this->relationship_filter;
    }

    public function hasRelationshipFilter()
    {
        return isset($this->relationship_filter);
    }

    public function clearRelationshipFilter()
    {
        unset($this->relationship_filter);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [json_name = "relationshipFilter", (.validate.rules) = {</code>
     * @param \Authzed\Api\V1\RelationshipFilter $var
     * @return $this
     */
    public function setRelationshipFilter($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\RelationshipFilter::class);
        $this->relationship_filter = $var;

        return $this;
    }

}

