<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/watchresources_service.proto

namespace Authzed\Api\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PermissionUpdate represents a single permission update for a specific
 * subject's permissions.
 *
 * Generated from protobuf message <code>authzed.api.v1alpha1.PermissionUpdate</code>
 */
class PermissionUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * subject defines the subject resource whose permissions have changed.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 1 [json_name = "subject"];</code>
     */
    protected $subject = null;
    /**
     * resource defines the specific object in the system.
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 2 [json_name = "resource"];</code>
     */
    protected $resource = null;
    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation"];</code>
     */
    protected $relation = '';
    /**
     * Generated from protobuf field <code>.authzed.api.v1alpha1.PermissionUpdate.Permissionship updated_permission = 4 [json_name = "updatedPermission"];</code>
     */
    protected $updated_permission = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V1\SubjectReference $subject
     *           subject defines the subject resource whose permissions have changed.
     *     @type \Authzed\Api\V1\ObjectReference $resource
     *           resource defines the specific object in the system.
     *     @type string $relation
     *     @type int $updated_permission
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1Alpha1\WatchresourcesService::initOnce();
        parent::__construct($data);
    }

    /**
     * subject defines the subject resource whose permissions have changed.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 1 [json_name = "subject"];</code>
     * @return \Authzed\Api\V1\SubjectReference|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * subject defines the subject resource whose permissions have changed.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 1 [json_name = "subject"];</code>
     * @param \Authzed\Api\V1\SubjectReference $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\SubjectReference::class);
        $this->subject = $var;

        return $this;
    }

    /**
     * resource defines the specific object in the system.
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 2 [json_name = "resource"];</code>
     * @return \Authzed\Api\V1\ObjectReference|null
     */
    public function getResource()
    {
        return $this->resource;
    }

    public function hasResource()
    {
        return isset($this->resource);
    }

    public function clearResource()
    {
        unset($this->resource);
    }

    /**
     * resource defines the specific object in the system.
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 2 [json_name = "resource"];</code>
     * @param \Authzed\Api\V1\ObjectReference $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation"];</code>
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>string relation = 3 [json_name = "relation"];</code>
     * @param string $var
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1alpha1.PermissionUpdate.Permissionship updated_permission = 4 [json_name = "updatedPermission"];</code>
     * @return int
     */
    public function getUpdatedPermission()
    {
        return $this->updated_permission;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1alpha1.PermissionUpdate.Permissionship updated_permission = 4 [json_name = "updatedPermission"];</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedPermission($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V1alpha1\PermissionUpdate\Permissionship::class);
        $this->updated_permission = $var;

        return $this;
    }

}

