<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/watchresources_service.proto

namespace Authzed\Api\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1alpha1\PermissionUpdate\Permissionship instead.
     * @deprecated
     */
    class PermissionUpdate_Permissionship {}
}
class_exists(PermissionUpdate\Permissionship::class);
@trigger_error('Authzed\Api\V1alpha1\PermissionUpdate_Permissionship is deprecated and will be removed in the next major release. Use Authzed\Api\V1alpha1\PermissionUpdate\Permissionship instead', E_USER_DEPRECATED);

