<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/schema.proto

namespace Authzed\Api\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ReadSchemaRequest is the required data to read Object Definitions from
 * a Schema.
 *
 * Generated from protobuf message <code>authzed.api.v1alpha1.ReadSchemaRequest</code>
 */
class ReadSchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of names of the Object Definitions that are being requested.
     * These names must be fully qualified with their namespace (e.g.
     * myblog/post).
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames", (.validate.rules) = {</code>
     */
    private $object_definitions_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $object_definitions_names
     *           The list of names of the Object Definitions that are being requested.
     *           These names must be fully qualified with their namespace (e.g.
     *           myblog/post).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1Alpha1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of names of the Object Definitions that are being requested.
     * These names must be fully qualified with their namespace (e.g.
     * myblog/post).
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames", (.validate.rules) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectDefinitionsNames()
    {
        return $this->object_definitions_names;
    }

    /**
     * The list of names of the Object Definitions that are being requested.
     * These names must be fully qualified with their namespace (e.g.
     * myblog/post).
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames", (.validate.rules) = {</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectDefinitionsNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->object_definitions_names = $arr;

        return $this;
    }

}

