<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/schema.proto

namespace Authzed\Api\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ReadSchemaResponse is the resulting data after having read the Object
 * Definitions from a Schema.
 *
 * Generated from protobuf message <code>authzed.api.v1alpha1.ReadSchemaResponse</code>
 */
class ReadSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The Object Definitions that were requested.
     *
     * Generated from protobuf field <code>repeated string object_definitions = 1 [json_name = "objectDefinitions"];</code>
     */
    private $object_definitions;
    /**
     * The computed revision of the returned object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     */
    protected $computed_definitions_revision = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $object_definitions
     *           The Object Definitions that were requested.
     *     @type string $computed_definitions_revision
     *           The computed revision of the returned object definitions.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1Alpha1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * The Object Definitions that were requested.
     *
     * Generated from protobuf field <code>repeated string object_definitions = 1 [json_name = "objectDefinitions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectDefinitions()
    {
        return $this->object_definitions;
    }

    /**
     * The Object Definitions that were requested.
     *
     * Generated from protobuf field <code>repeated string object_definitions = 1 [json_name = "objectDefinitions"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->object_definitions = $arr;

        return $this;
    }

    /**
     * The computed revision of the returned object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     * @return string
     */
    public function getComputedDefinitionsRevision()
    {
        return $this->computed_definitions_revision;
    }

    /**
     * The computed revision of the returned object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     * @param string $var
     * @return $this
     */
    public function setComputedDefinitionsRevision($var)
    {
        GPBUtil::checkString($var, True);
        $this->computed_definitions_revision = $var;

        return $this;
    }

}

