<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/watchresources_service.proto

namespace Authzed\Api\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * WatchResourcesRequest starts a watch for specific permission updates
 * for the given resource and subject types.
 *
 * Generated from protobuf message <code>authzed.api.v1alpha1.WatchResourcesRequest</code>
 */
class WatchResourcesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * resource_object_type is the type of resource object for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string resource_object_type = 1 [json_name = "resourceObjectType", (.validate.rules) = {</code>
     */
    protected $resource_object_type = '';
    /**
     * permission is the name of the permission or relation for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string permission = 2 [json_name = "permission", (.validate.rules) = {</code>
     */
    protected $permission = '';
    /**
     * subject_object_type is the type of the subject resource for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string subject_object_type = 3 [json_name = "subjectObjectType"];</code>
     */
    protected $subject_object_type = '';
    /**
     * optional_subject_relation allows you to specify a group of subjects to watch
     * for a given subject type.
     *
     * Generated from protobuf field <code>string optional_subject_relation = 4 [json_name = "optionalSubjectRelation"];</code>
     */
    protected $optional_subject_relation = '';
    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 5 [json_name = "optionalStartCursor"];</code>
     */
    protected $optional_start_cursor = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource_object_type
     *           resource_object_type is the type of resource object for which we will
     *           watch for changes.
     *     @type string $permission
     *           permission is the name of the permission or relation for which we will
     *           watch for changes.
     *     @type string $subject_object_type
     *           subject_object_type is the type of the subject resource for which we will
     *           watch for changes.
     *     @type string $optional_subject_relation
     *           optional_subject_relation allows you to specify a group of subjects to watch
     *           for a given subject type.
     *     @type \Authzed\Api\V1\ZedToken $optional_start_cursor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1Alpha1\WatchresourcesService::initOnce();
        parent::__construct($data);
    }

    /**
     * resource_object_type is the type of resource object for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string resource_object_type = 1 [json_name = "resourceObjectType", (.validate.rules) = {</code>
     * @return string
     */
    public function getResourceObjectType()
    {
        return $this->resource_object_type;
    }

    /**
     * resource_object_type is the type of resource object for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string resource_object_type = 1 [json_name = "resourceObjectType", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setResourceObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_object_type = $var;

        return $this;
    }

    /**
     * permission is the name of the permission or relation for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string permission = 2 [json_name = "permission", (.validate.rules) = {</code>
     * @return string
     */
    public function getPermission()
    {
        return $this->permission;
    }

    /**
     * permission is the name of the permission or relation for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string permission = 2 [json_name = "permission", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPermission($var)
    {
        GPBUtil::checkString($var, True);
        $this->permission = $var;

        return $this;
    }

    /**
     * subject_object_type is the type of the subject resource for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string subject_object_type = 3 [json_name = "subjectObjectType"];</code>
     * @return string
     */
    public function getSubjectObjectType()
    {
        return $this->subject_object_type;
    }

    /**
     * subject_object_type is the type of the subject resource for which we will
     * watch for changes.
     *
     * Generated from protobuf field <code>string subject_object_type = 3 [json_name = "subjectObjectType"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_object_type = $var;

        return $this;
    }

    /**
     * optional_subject_relation allows you to specify a group of subjects to watch
     * for a given subject type.
     *
     * Generated from protobuf field <code>string optional_subject_relation = 4 [json_name = "optionalSubjectRelation"];</code>
     * @return string
     */
    public function getOptionalSubjectRelation()
    {
        return $this->optional_subject_relation;
    }

    /**
     * optional_subject_relation allows you to specify a group of subjects to watch
     * for a given subject type.
     *
     * Generated from protobuf field <code>string optional_subject_relation = 4 [json_name = "optionalSubjectRelation"];</code>
     * @param string $var
     * @return $this
     */
    public function setOptionalSubjectRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_subject_relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 5 [json_name = "optionalStartCursor"];</code>
     * @return \Authzed\Api\V1\ZedToken|null
     */
    public function getOptionalStartCursor()
    {
        return $this->optional_start_cursor;
    }

    public function hasOptionalStartCursor()
    {
        return isset($this->optional_start_cursor);
    }

    public function clearOptionalStartCursor()
    {
        unset($this->optional_start_cursor);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 5 [json_name = "optionalStartCursor"];</code>
     * @param \Authzed\Api\V1\ZedToken $var
     * @return $this
     */
    public function setOptionalStartCursor($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->optional_start_cursor = $var;

        return $this;
    }

}

