<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authzed/api/v1alpha1/schema.proto

namespace Authzed\Api\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * WriteSchemaResponse is the resulting data after having written a Schema to
 * a Permissions System.
 *
 * Generated from protobuf message <code>authzed.api.v1alpha1.WriteSchemaResponse</code>
 */
class WriteSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The names of the Object Definitions that were written.
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames"];</code>
     */
    private $object_definitions_names;
    /**
     * The computed revision of the written object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     */
    protected $computed_definitions_revision = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $object_definitions_names
     *           The names of the Object Definitions that were written.
     *     @type string $computed_definitions_revision
     *           The computed revision of the written object definitions.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzed\Api\V1Alpha1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * The names of the Object Definitions that were written.
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectDefinitionsNames()
    {
        return $this->object_definitions_names;
    }

    /**
     * The names of the Object Definitions that were written.
     *
     * Generated from protobuf field <code>repeated string object_definitions_names = 1 [json_name = "objectDefinitionsNames"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectDefinitionsNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->object_definitions_names = $arr;

        return $this;
    }

    /**
     * The computed revision of the written object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     * @return string
     */
    public function getComputedDefinitionsRevision()
    {
        return $this->computed_definitions_revision;
    }

    /**
     * The computed revision of the written object definitions.
     *
     * Generated from protobuf field <code>string computed_definitions_revision = 2 [json_name = "computedDefinitionsRevision"];</code>
     * @param string $var
     * @return $this
     */
    public function setComputedDefinitionsRevision($var)
    {
        GPBUtil::checkString($var, True);
        $this->computed_definitions_revision = $var;

        return $this;
    }

}

